### ISSUE TITLE
Cannot get metric values from script

### ISSUE THREAD

**Issue by pavel-mutafchiev** [emc-openstack/storops#190]
Hello, 

I am getting all NaN values when trying to poll unity metrics via a python script using your library, at the same time I am able to execute the exact same commands in ipython and they do output values different than NaN.

I assume it's something I'm missing. I posting the wip version of the script below.

#!/usr/bin/python
import requests
import urllib3

from storops import UnitySystem
urllib3.disable_warnings()

unity = UnitySystem('x.x.x.x', 'u', 'p')
unity.enable_perf_stats(interval=None, rsc_clz_list=None)

#print unity
#pools = unity.get_pool()
#disks=unity.get_disk()
#sps=unity.get_sp()

fcs=unity.get_fc_port()
#print fcs
fc1=fcs[0]
fc2=fcs[1]
fc3=fcs[2]
fc4=fcs[3]
print fc1
print fc2
print fc3
print fc4

#var=fc1.get_metric_value("write_iops")
#print var

#fcbin=fcs[0].get_metric_value("read_byte_rate")
#print fcbin

**Comment by yong-huang** [comment]
Hello,

After unity.enable_perf_stats() is invoked, storops start to collect realtime metric data, interval is one minute, you have to wait two intervals for data collection, then storops will calculate the delta data and return the value.
So suggest waiting two or more minutes before using the metric data.

**Comment by pavel-mutafchiev** [comment]
Thanks, 

I kinda figured it out via trial and error by sticking a sleep and increasing it gradually till it reached 3 minutes.

Is there a way to lower the collection interval perhaps? I'm trying to gather metric data for a monitoring system and some of the metrics I'd rather have more than once per minute.

**Comment by yong-huang** [comment]
You can specify the interval when invoking unity.enable_perf_stats(interval=xx), but not suggest specifying interval lower than one minute, because when unity.enable_perf_stats() invoked, storops will start asynchronous job to register to Unity for metric data subscription, then start data collection. If interval less than one minutes, the registration may not finished, some metric data may not be collected.
Anyway, you can try specifying a lower interval, and give us a feedback, thanks.

**Comment by pavel-mutafchiev** [comment]
Hey,

I successfully gather metrics from UnitySystem with a 30 second collection interval without any evident issues. 

Thanks for your help.
