### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by lriva94** [emc-openstack/storops#264]
storops 1.1.0 on Centos 7 and Python 3.6 from IUS

I get the following two warnings when using the VNX part of the module:
/usr/lib/python3.6/site-packages/storops/lib/parser.py:360: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  ret = yaml.load(stream)
/usr/lib/python3.6/site-packages/storops/lib/metric.py:199: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  ret = yaml.load(stream)

In each line I replaced with the following code:
ret = yaml.load(stream, Loader=yaml.FullLoader)

Maybe another value for Loader is more accurate...

This is explained at the following page:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Thanks

**Comment by Murray-LIANG** [comment]
Thanks for the notification.

Some old versions of OpenStack env are using PyYAML==3.10, and storops still supports those versions. So we cannot change the `load` to `load(Loader=FullLoader)` directly because there is no `FullLoader` in PyYAML 3.10.

The latest version PyYAML uses `FullLoader` after printing the deprecated warning message. `FullLoader` is also the loader that will be used in the future release of storops. So currently storops works under the latest PyYAML except the warning message.

We'll eliminate the warning by adding a wrapper working under both versions of `pyyaml.load`.

**Comment by Murray-LIANG** [comment]
Use `SafeLoader` for security concerns.
