### ISSUE TITLE
No handlers could be found for logger "storops.vnx.navi_command"

### ISSUE THREAD

**Issue by sunnyrarora** [emc-openstack/storops#6]
Hi Team,
I have sucessfully installed storops and also haveing naviseccli on the RHEL6.7.
Every time I am getting message "No handlers could be found for logger "storops.vnx.navi_command"

And it get stucks, sometimes i get the output but sometimes not.

```
[root@Test ~]# python2.7
Python 2.7.10 (default, May 27 2016, 05:55:08)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>> from storops import VNXSystem
>>> vnx = VNXSystem('10.xx.xx.xx', 'test_user', 'password')
>>> vnx
No handlers could be found for logger "storops.vnx.navi_command"
```
Thanks
Sunny

**Comment by jealous** [comment]
Hi Sunny,

The error for handlers not found is that the library wants to print some log but the log handler is not configured.  Using following log would configure and print the INFO level log.  You could check the document of logging module for more logging configuration.
``` python
import logging
logging.basicConfig(level=logging.INFO)
```

For the stuck problem, it's usually caused by security level.  Please check your security level with following command:
```
naviseccli security -certificate -getLevel
```
If the output is not `low`, please update the security level to `low` with following command.
```
naviseccli security -certificate -setLevel low
```
The reason is that if security level is not `low`, naviseccli will prompt a certificate confirmation for the array that never connected before.  And storops stuck at the prompt.

If the securty level is already set to `low` and the issue is not resolved, please help to set the log level to `DEBUG` and paste the log in this thread.  Thanks.

Let me know if the problem is resolved.  Thanks.
Cedric

**Comment by sunnyrarora** [comment]
Hi Jealous/Cedric,
Thank you for the reply. Yes, After changing the naviseccli security to low, Its working fine. Now getting proper response.
I also ran
```
import logging
logging.basicConfig(level=logging.INFO)

```
Just one more aspect, now i am also getting continues messages on console within some interval. 
```
INFO:storops.vnx.navi_command:call command: /opt/Navisphere/bin/naviseccli -h 10.xx.xx.xx -user test_user -password *** -scope 0 -np getagent
INFO:storops.vnx.navi_command:call command: /opt/Navisphere/bin/naviseccli -h 10.xx.xx.xx -user test_user -password *** -scope 0 -np getagent
INFO:storops.vnx.navi_command:call command: /opt/Navisphere/bin/naviseccli -h 10.xx.xx.xx -user test_user -password *** -scope 0 -np getagent
```

Thanks
Sunny

**Comment by jealous** [comment]
Hi Sunny,

The periodic log records the heartbeat used by the library to determine whether SPs are alive.
You could turn that off by setting the log level to `WARNING` or set the heartbeat interval to 0.

Cedric

**Comment by sunnyrarora** [comment]
Thanks Cedric,
I was able to resolve the issue .
